### ISSUE TITLE
[UI Bug] CreateShopSyncActivity: Edit text view shouldn't bounce to top of the screen 

### ISSUE THREAD

**Issue by JohnLavender474** [JohnLavender474/ShopSync#30]
In the CreateShopSyncActivity, when the user clicks on the "Invite User +"  button, an edit text view is created towards the bottom half of the screen. Currently, when the user clicks on that edit text view, it bounces towards the top of the screen. This creates a rather ugly interface. This should be fixed.

Before click:
<img width="365" alt="Screen Shot 2023-11-29 at 1 38 17 PM" src="https://github.com/JohnLavender474/ShopSync/assets/82977289/dba6b212-e8f7-434d-8886-3071f6f4d90a">

After click:
<img width="365" alt="Screen Shot 2023-11-29 at 1 38 23 PM" src="https://github.com/JohnLavender474/ShopSync/assets/82977289/470c0402-7041-4801-8fd0-74cb2c3f1f23">

**Comment by EdisMake** [comment]
resolved
